project06/config/routes.rb
Gamez::Application.routes.draw do
  resources :ratings
  
  resources :games

  resources :roles

  resources :users
  
  resources :user_sessions
  
  controller :user_sessions do
    get 'login' => :new
    get 'logout' => :destroy
  end

  root :to => 'games#index'
  

  
 
  
end

project06/app/models/rating.rb
class Rating < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true
end

project06/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  filter_resource_access
  
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :ok }
    end
  end
end

project06/app/helpers/ratings_helper.rb
module RatingsHelper
end

project06/app/views/ratings/_form.html.haml
= form_for @rating do |f|
  -if @rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"
      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

project06/app/views/ratings/edit.html.haml
%h1 Editing rating

= render 'form'

= link_to 'Show', @rating
\|
= link_to 'Back', ratings_path

project06/app/views/ratings/index.html.haml
%h1 Listing ratings

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @ratings.each do |rating|
    %tr
      %td= rating.name
      %td= link_to 'Show', rating
      %td= link_to 'Edit', edit_rating_path(rating)
      %td= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Rating', new_rating_path

project06/app/views/ratings/new.html.haml
%h1 New rating

= render 'form'

= link_to 'Back', ratings_path

project06/app/views/ratings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @rating.name

= link_to 'Edit', edit_rating_path(@rating)
\|
= link_to 'Back', ratings_path